name: Add comment to newly created issue using community action or Github API
on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  # Add_Comment_To_Issue_Using_Community_Action:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print github event context
  #       run: echo '${{ toJSON(github.event) }}' | jq
  #       shell: bash
  #     - name: Create comment
  #       uses: peter-evans/create-or-update-comment@v3.1.0
  #       with:
  #         issue-number: ${{ github.event.issue.number }}
  #         body: |
  #           This is a multi-line test comment
  #           - With GitHub **Markdown** :sparkles:
  #           - Created by [create-or-update-comment][1]

  #           [1]: https://github.com/peter-evans/create-or-update-comment
  #         reactions: '+1'
  Add_comment_to_issue_using_github_api:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment using github api
        run: |
          gh api -X POST \
          http://api.github.com/repos/${OWNER}/${REPO}/issues/${issue_number}/comments \
          -f body='COMMENT ADDED....'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.issue.number }}
          
  
